### ISSUE TITLE
Error Message while adding a mite account in preferences

### ISSUE THREAD

**Issue by teemow** [thomasklein/Trac2mite#1]
On the Preferences -> Mite tab – when I add my mite credentials I've got this error message:

AttributeError: 'NoneType' object has no attribute 'account_name' 

<pre>
File "/usr/lib/python2.6/dist-packages/trac/web/main.py", line 444, in _dispatch_request
  dispatcher.dispatch(req)
File "/usr/lib/python2.6/dist-packages/trac/web/main.py", line 205, in dispatch
  resp = chosen_handler.process_request(req)
File "/usr/lib/python2.6/dist-packages/trac/prefs/web_ui.py", line 73, in process_request
  template, data = chosen_provider.render_preference_panel(req, panel_id)
File "/var/trac/digitalcube/cooltra/plugins/Trac2mite/0.11/trac2mite/web_ui.py", line 71, in render_preference_panel
  if self.prefs.account_name != None:
</pre>

The Trac install is on Ubuntu:

<pre>
Trac:   0.11.5
Python: 2.6.4 (r264:75706, Dec 7 2009, 18:59:58) [GCC 4.4.1]
setuptools: 0.6c9
SQLite: 3.6.16
pysqlite:   2.4.1
Genshi: 0.5.1
mod_python: 3.3.1
Pygments:   1.0
Subversion: 1.6.5 (r38866)
jQuery: 1.3.2
</pre>

Trac2mite plugin is
SHA: 57ac2a62bdaea3a62b2ed666b10900827f10d704

Accountmanager Plugin is also installed

However I just tried it again and now it works. But this happens with every new user, but only for the first time.

**Comment by thomasklein** [comment]
Hi Timo - thanks for your message!
I have for some reason trouble setting up the Accountmanager-Plugin, so i can't reproduce your error. If i add a new user with htpasswd, there are no problems.
However, i will try to get the Accountmanager-Plugin running and examine this issue!
